# Generated by Django 4.2.1 on 2023-08-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_hospital_information_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_info',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, choices=[('Psychiatrist', 'Psychiatrist'), ('Clinical Psychologist', 'Clinical Psychologist'), ('Therapist', 'Therapist'), ('Marriage and Family Therapist (MFT)', 'Marriage and Family Therapist (MFT)'), ('Child and Adolescent Psychiatrist', 'Child and Adolescent Psychiatrist'), ('Neuropsychologist', 'Neuropsychologist')], max_length=70, null=True)),
                ('featured_image', models.ImageField(blank=True, default='doctors/user-default.png', null=True, upload_to='doctors/')),
                ('certificate_image', models.ImageField(blank=True, default='doctors_certificate/default.png', null=True, upload_to='doctors_certificate/')),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nid', models.CharField(blank=True, max_length=70, null=True)),
                ('visiting_hour', models.CharField(blank=True, max_length=50, null=True)),
                ('consultation_fee', models.IntegerField(blank=True, null=True)),
                ('report_fee', models.IntegerField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('institute', models.CharField(blank=True, max_length=70, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_year', models.CharField(blank=True, max_length=100, null=True)),
                ('work_place', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('start_year', models.CharField(blank=True, max_length=50, null=True)),
                ('end_year', models.CharField(blank=True, max_length=50, null=True)),
                ('register_status', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital_department')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.specialization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='hospital.userp')),
            ],
        ),
    ]
