# Generated by Django 4.2.1 on 2023-08-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
