# Generated by Django 4.2.1 on 2023-08-21 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_doctorexperience_doctoreducation'),
        ('hospital', '0006_alter_patient_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.CharField(max_length=50)),
                ('medicine_name', models.CharField(max_length=200)),
                ('quantity_per_day', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('relation_with_meal', models.CharField(max_length=50)),
                ('instruction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_pdf', models.FileField(upload_to='reports/')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor_info')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
