# Generated by Django 4.2.1 on 2023-08-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_password_patient_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Information',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('featured_image', models.ImageField(blank=True, default='hospitals/default.png', null=True, upload_to='hospitals/')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('hospital_type', models.CharField(choices=[('private', 'Private hospital'), ('public', 'Public hospital')], max_length=200)),
                ('general_bed_no', models.IntegerField(blank=True, null=True)),
                ('available_icu_no', models.IntegerField(blank=True, null=True)),
                ('regular_cabin_no', models.IntegerField(blank=True, null=True)),
                ('emergency_cabin_no', models.IntegerField(blank=True, null=True)),
                ('vip_cabin_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_department',
            fields=[
                ('hospital_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_department_name', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='departments/default.png', null=True, upload_to='departments/')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information')),
            ],
        ),
    ]
