# Generated by Django 4.2.1 on 2023-08-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_userp_demo_alter_userp_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='featured_image',
            field=models.ImageField(blank=True, default='static/image/profile_default.svg', null=True, upload_to='edit_profile/'),
        ),
    ]
