# Generated by Django 4.2.1 on 2023-08-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hospital', '0004_userp_demo_alter_userp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='demo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userp',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_q_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userp',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_q_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
