# Generated by Django 4.2.1 on 2023-08-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_patient_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
