# Generated by Django 4.2.1 on 2023-08-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_hospital_information_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
