# Generated by Django 4.2.1 on 2023-08-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_hospital_information_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
