# Generated by Django 4.2.1 on 2023-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_hospital_information_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_department',
            name='hospital_department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
