# Generated by Django 4.2.1 on 2023-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctor_info_specialization'),
        ('hospital', '0010_alter_hospital_department_hospital_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_department',
            name='hospital_department_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='specialization',
        ),
    ]
