# Generated by Django 4.2.1 on 2023-08-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorexperience_doctoreducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_info',
            name='login_status',
            field=models.CharField(blank=True, default='offline', max_length=200, null=True),
        ),
    ]
