# Generated by Django 4.2.1 on 2023-08-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_info_login_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_info',
            name='specialization',
        ),
    ]
